uwcsc/codeybot

.eslintrc
.github/workflows/build.yml
package.json
src/bot.ts
src/components/db.ts
src/logger.ts
yarn.lock

Added a CI job to lint, format, and typescript build the app.
Added `yarn format` and `yarn lint` to automatically fix linting and formatting issues locally.

Add github workflow for CI checks

---

.github/pull_request_template.md

N/A
Change this title ^ to Summary of Changes instead.
N/A

Update PR template summary instead of descriptions

---

.github/ISSUE_TEMPLATE/feature_request.md

N/A
Feature request -> Feature Request
N/A

capitalize feature request

---

src/components/db.ts
src/components/interview.ts

resolves https://github.com/uwcsc/codeybot/issues/5
resolves https://github.com/uwcsc/codeybot/issues/4
Add comments to interview.ts
Add functionality to clear interviewer data 
Add functionality to add expertise domain 
Add functionality to filter by expertise domain
Add functionality to view own calendar link and domains
```
//create interviewer profile
.interviewer signup YOUR_CALENDLY_OR_XAI_LINK
//add domains
.interviewer domain [frontend/backend/pm/design]
//filter by domain
.interviewer list (frontend/backend/pm/design)
//view own profile
.interviewer profile
//clear profile
.interviewer clear
```

Interviewer modify and query by expertise domains

---

README.md
package.json
src/bot.ts
src/commands/suggestions/suggestionList.ts
src/commands/suggestions/utils.ts
src/components/cron.ts
src/components/suggestions.ts
yarn.lock

Resolves https://github.com/uwcsc/codeybot/issues/6.
Created a scheduled command that runs once every minute to change 'Created' suggestions into 'Pending' suggestions.
Makes a notif in the same channel for now after at least one suggestion state was changed.
.suggest 3 random things, and then:
Ensure your new suggestions are created in the same minute, and after a minute, a notification will appear, showing the new suggestions.
.suggestions again to make sure states have changed to pending

Cron suggestion state

---

src/components/interview.ts

Resolves https://github.com/uwcsc/codeybot/issues/38
Added a few more interviewer domains
.interviewerdomain

add datasci and infra as new domains

---

src/components/interview.ts

Resolves https://github.com/uwcsc/codeybot/issues/38
Added new domains, and fixed domain help messages to be code blocks

add domains and fix help messages

---

.github/workflows/build.yml
README.md

N/A
Added github action status badge to README
See `README.md`

add github action badge

---

src/commands/suggestions/suggestionsUpdate.ts
src/commands/suggestions/utils.ts
src/components/suggestions.ts

https://github.com/uwcsc/codeybot/issues/10
Created Suggestion Update Command
.suggestions-update <state> <IDs>

Suggestion state update

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml

resolves #36 
Deploys codey to production on new releases. Using the release tag as the docker image tag.
Make a new release.

Deploy codey to production on new release

---

.github/workflows/deploy-production.yml

N/A
Fixing #51 
Make a release.

Fix release ref

---

.github/workflows/deploy-production.yml

N/A
Fixing #51 
Make a release.

trim prefix

---

config/owners.yml

Resolves #64 
Added myself to the owners.yml file
N/A

Added Picowchew to owners.yml

---

config/owners.yml

i have done as i was told mr dankat

Add Mark to Owners

---

src/commands/interviews/interviewerClear.ts
src/commands/interviews/interviewerDomain.ts
src/commands/interviews/interviewerPause.ts
src/commands/interviews/interviewerProfile.ts
src/commands/interviews/interviewerResume.ts
src/commands/interviews/interviewerSignup.ts
src/commands/interviews/interviewers.ts

N/A
Added more aliases to the interview commands
Try the aliases as listed in the files of `src/commands/interviews/`

Added interview aliases

---

src/bot.ts
src/commands/fun/flipCoin.ts

Resolves #96 
Added the `.flip-coin` command
Run `.flip-coin`

Added flip-coin

---

package.json
src/bot.ts
src/commands/games/blackjack.ts
src/components/games/blackjack.ts
yarn.lock

resolves #105 
- Added a `.blackjack` or .`blj <amount>` command to start a blackjack game.
- Players can bet any amount between 10 and 1,000,000 inclusive.
- Players can react to H to hit, S to stand, or Q to quit.
Start the bot and use `.blj`

Blackjack game using codey coins

---

config/owners.yml

Onboarding: First Task
Added Edwin to the owners file
List the steps needed for the reviewer to produce your PR changes.

added EDWIN to owners.yml

---

src/commands/coin/coinAdjust.ts
src/commands/coin/coinUpdate.ts
src/commands/games/blackjack.ts
src/components/coin.ts
src/components/db.ts
src/components/suggestions.ts

Resolves #115 
- Created the `user_coin_ledger` table with the following schema, noting that there is an index on `user_id`:
**id: number PK NOT NULL**
user_id: string NOT NULL
amount: number NOT NULL
new_balance: number NOT NULL
event: enum NOT NULL
reason: string
admin_id: string
created_at: datetime NOT NULL
- Removed the `updated_at` column from the `user_coin` table because this information can now be found in the `user_coin_ledger` table
- Made all of the timestamp columns in the tables not null
- Fixed coin-adjust's examples in its help message
- Minor grammar fix
- Execute the SQL commands:
`ALTER TABLE user_coin DROP COLUMN updated_at;`
`CREATE TABLE suggestions2 (id INTEGER PRIMARY KEY NOT NULL, author_id VARCHAR(255) NOT NULL, author_username TEXT NOT NULL, created_at TIMESTAMP …

Added ledger for Codey coin

---

.eslintrc
src/bot.ts
src/commands/coin/coinAdjust.ts
src/components/coin.ts
src/components/cron.ts

Resolves #121 
A daily Codey coin bonus is given to those on the interviewer list
At 1 am UTC, see the bonus being given

Daily Codey coin bonus to those on interviewer list

---

src/components/coin.ts
src/components/cron.ts

N/A
Fixed the interviewer list bonus being attempted to be applied as an activity bonus, in which an error is thrown because the interviewer list bonus does not have a cooldown
Send some messages and see that an error is not thrown anymore

Fixed interviewer list bonus being applied as activity bonus

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

N/A
Issues created from issue templates were automatically assigned to Kallen, we need to update them so they get assigned to Andy instead.
Try creating an issue from template

Auto assign template issues to asdera

---

config/owners.yml

N/A Onboarding :)
I added my (Allen Lu) discord id number to the owners.yml
First Pr! (Woohoo) 🎉
Go to owners.yml and paste in the secret sauce

added Caillou to the owners.yml

---

src/commands/coin/coinInfo.ts

resolves #91 
Added a .coin-info command that shows an embed with:
-Ways to get Codey coins.
-How to spend Codey coins.
run .coin-info

added coin-info command and embed

---

config/owners.yml

added Danielk1345 to owners.yml

added Danielk1345 to owners.yml

---

config/owners.yml

Added gnishiwaki to codeybot
Included discord id into owners.yml
Approve the change

added gnishiwaki to owners.yml

---

src/components/profile.ts

Fixed a potential injection since we were not using wildcards in one location.
- Try running .profile set aboutme hello', program = 'fail
- Notice that your aboutme is set, but your program is not changed to fail.

fixed possible injection

---

.github/pull_request_template.md

Resolves #212 
Descriptions in the PR template are now commented out
The changes should be seen when making a new PR

Commented out descriptions in PR template

---

config/owners.yml

Issue(s) that this PR will resolve, e.g. "resolves <issue link here>".
A summary or description of changes made in this PR.
List the steps needed for the reviewer to produce your PR changes.

added WWW0030 to owners.yml

---

package.json
src/bot.ts
src/codeyCommand.ts
src/commands/ping/ping.ts
yarn.lock

Changed the `ping` command to a slash command as a proof of concept.
I used [this guide](https://www.sapphirejs.dev/docs/Guide/getting-started/creating-a-basic-app-command) for reference.
1. Build and run the bot
2. Run `/ping`
The biggest caveat for this PR is that this requires Sapphire v3, which is currently in beta. That being said, in the Sapphire server the people I talked to mentioned Sapphire v3 is stable and should be officially released soon.

Added ping slash command (POC)

---

README.md

N/A
Added OFFICE_CHANNEL_ID to README.md so people know to add it to the config
N/A

Added OFFICE_CHANNEL_ID to README.md

---

src/commands/miscellaneous/help.ts

Resolves #223 
Added the help command that provides the URL to the wiki page
`.help` and `.wiki` should work (as well as their slash command version)

Added help command

---

.github/pull_request_template.md

N/A
Added to the PR template a reminder to include screenshots if possible
The changes should be seen when making future PRs

Added reminder for screenshot

---

src/codeyCommand.ts

N/A
Modified codeyCommand so that messages from non-slash commands are not edited anymore
Try out non-slash commands

Do not edit messages anymore

---

src/components/cron.ts

add additional error state for when API endpoint breaks

---

src/commands/suggestion/suggestion.ts

Resolves #238 
Fixed non-administrators being able to update and list suggestions
Try the suggestion commands with and without administrator permission

Fixed suggestion admin permission

---

src/utils/github.ts

resolves #255 
Caches github info and release daily to prevent rate limiting.

add daily lazy loading to github

---

docker/production/Dockerfile

resolves #67 
Update dockerfile for production to use yarn.
Will have to monitor to ensure stability once new release is authored.

update prod dockerfile:

---

src/utils/github.ts

Correctly activates lazy loading of github info after a day

fix github loading

---

src/listeners/messageCreate.ts

Codey staging dies if resume pdf has > 2 pages
So we now assert resume is 1 page

Resume staging fixes

---

src/commandDetails/coin/check.ts
src/commandDetails/coin/leaderboard.ts

Fixed coin check and leaderboard to account for invalid users.

Fixes to coin commands

---

.github/workflows/addCreatedIssueToBacklog.yml

another version number fix, added "v" in front of 0.3.0

Add issue to backlog update version number, attempt 2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

N/A
Refactor github templates.
- used comments instead of italics text to indicate the behaviour the submitter is expected to follow
- used `##` instead of bold text to indicate subsections
- more concise
- minor re-ordering to favour `Summary of changes` over linked Issues
- added motivation and  additional comments sections

meta: Update Github PR/Issue templates

---

src/components/games/blackjack.ts

Gets rid of the logs made by blackjack.
Blackjack logs create clutter when trying to debug and aren't that useful
Resolves #318

feat(blackjack): get rid of logs

---

.gitignore
src/commandDetails/coin/update.ts

Resolving the coin update 0 issue #291 
changed boolean check in line 26 of src/commandDetails/coin/update.ts to a typecheck.
coin update 0 should now work correctly.
I want to additionally say, that i just guessed that the attributes are converted before passing them into commands.
Tell me if i did a mistake.

[Resolving Bug #291]: Corrected if block.

---

.dockerignore

added dist to dockerignore

---

.dockerignore

Fixed .dockerignore tmp and dist

---

README.md
docs/SETUP.md

- Transferred setup information from `README.md` to `SETUP.md`
- Modified the `vars.json` instructions for local configuration, since we now have `vars.template.json`
- Modified the description of `IRC_USER_ID` to make it more clear that it is the user ID of a bot
- Modified some headers in `README.md` to be more concise
This should make onboarding more straightforward.
Resolves #348 
N/A
N/A

Transferred setup information from README.md to SETUP.md

---

.github/workflows/build.yml

Changed `master` to `main` in `build.yml`
This is so that the pipeline runs when it is supposed to
Resolves #351 
N/A
N/A

Changed master to main in build.yml

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-staging.yml
README.md
docs/CONTRIBUTING.md
src/commands/miscellaneous/info.ts

Changed other instances of `master` to `main`, so not just the one from #351
Things broken from the branch renaming should work properly now
Resolves #354 
N/A
N/A

Changed other instances of master to main

---

docs/CONTRIBUTING.md

Added that branch name should be prefixed with the issue # in `CONTRIBUTING.md`
This visual indicator would help with more easily relating PRs with their issue #
Resolves #362 
N/A
N/A

Added issue # in branch name to docs

---

src/components/admin.ts

Removed newline from the ban message that is received in DMs
The newline was not supposed to be there
Resolves #367 
Try the `ban` command

Removed newline from ban message

---

src/components/cron.ts

Fixed office status update by preventing rate limiting, so made the time interval of the cron job be 10 minutes instead of 1, and adding `await`
Fixed office status update being delayed
Resolves #369 
N/A
N/A

Fixed office status update

---

.github/CODEOWNERS

Made @mcpenguin and @Picowchew the default reviewers for PRs
We will be the new leads and this would save PR creators some clicks
Resolves #374 
N/A
N/A

Made mcpenguin and Picowchew the default reviewers for PRs

---

src/components/cron.ts

issue fixes : #384 
Office status API link updated (https://csclub.ca/office-status/json)

office status API link updated

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Removed redundant labels
Less redundancy when creating issues
Resolves <https://github.com/uwcsc/codeybot/issues/325>
Create a new issue, observe that the title no longer gets an automatic prefix of [BUG] or [FEATURE]

removed redundant labels

---

tsconfig.json

Remove exclusion of src/oldCode from tsconfig.json
Just deleted code ^-^

#298 fixed

---

src/commandDetails/coin/leaderboard.ts
src/components/coin.ts

Changed the model of `UserCoinEntry` to add a rank field and updated the SQL query to get the rank of the user. Updated the `getUserIdCurrentCoinPosition` to get the current rank of the user based on the Rank() function of SQL. 
To resolve the issue #301

issue 301 coin leaderboard resolved

---

src/commandDetails/miscellaneous/uptime.ts
src/commands/miscellaneous/uptime.ts

Introduced /uptime command.
Gives a misc command to check Codey's uptime.
Call /uptime

Built /uptime command

---

src/components/db.ts

Added a helper function `addSQLColumnIfNotExists` in `db.ts` to add a column if it does not exist in the database table. 
This will allow developers to use this function and add columns without having to write the entire logic. 
#418 
The profile emoji functionality seems to be working fine.

Added functionality to dynamically add columns

---

docs/SETUP.md

- Added descriptions for `OFFICE_PING_ROLE_ID` and `RESUME_CHANNEL_ID`
- Updated descriptions for `COFFEE_ROLE_ID` and `OFFICE_STATUS_CHANNEL_ID`
This would help with the onboarding process when setting up the bot
Resolves #394 
N/A
N/A

Updated config variable descriptions in SETUP.md

---

README.md

Fixed images in README.md
Improved Documentation
resolves #430 
-N.A
A beginner here, would like to contribute to open source projects!!!

Fixed Images in README.md

---

src/commands/profile/profile.ts

Removed an unnecessary console.trace statement. 
To remove debug code that is not being used. 
resolves #442

console trace statement removed

---

src/commands/games/blackjack.ts
src/components/games/blackjack.ts

Fixed bj bugs in prod.
it's a prod bug lol
Resolves #446 
Bugs listed in issue should now be fixed.

446 Resolving bj bug

---

src/codeyCommand.ts
src/commandDetails/profile/about.ts
src/commandDetails/profile/grad.ts
src/commandDetails/profile/set.ts
src/commands/profile/profile.ts

Build slash command for `profile` by making three separate command details and updating the existing profile.ts
resolves #248 
Check out all slash commands for profile
Set
About
Grad

Slashify User Profile command

---

.eslintrc
src/commandDetails/coin/transfer.ts
src/commands/coin/coin.ts

Added transfer subcommand to coin. Includes checking for valid coin values (leq than user balance and geq 1) and the recipient is not the user. Currently does not include receiver confirmation, to be implemented.
Issue #307
Modified files: 
src/commands/coin.ts: added example coin transfer commands
.eslintrc: prettier formatting
New files:
src/commandDetails: transfer feature functionality

Issue# 307 (no confirmation)

---

.eslintrc
src/codeyCommand.ts
src/commandDetails/company/add.ts
src/commandDetails/company/find.ts
src/commandDetails/company/profile.ts
src/components/cron.ts

Removed console.log messages and added a rule for the linter to warn against console.log/error lines in the code.
We should not be pushing debug messages to main.
Resolves #457

removed console log and added linter rule

---

src/codeyCommand.ts
src/commandDetails/coin/transfer.ts
src/components/coin.ts

Update transfer embed to show the receiver and the transfer reason if applicable. Modify codeyCommand for regular commands to take all remaining arguments given on the last argument option.
Previously closed, but issue #307
(the transfers were manually rejected)

Adding 'To' and conditional 'Reason' fields to transfer embed

---

package.json
src/commandDetails/games/connectFour.ts
src/commands/games/connectFour.ts
src/components/db.ts
src/components/games/connectFour.ts
src/interaction-handlers/games/connectFour.ts
src/interaction-handlers/games/rps.ts
yarn.lock

src/commands/games/connectFour.ts: Connect 4 command
src/commandDetails/games/connectFour.ts: Connect 4 command details
src/components/games/connectFour.ts: 
- Game Tracker
- start a game
- end a game
- Game: 
- setStatus which checks for a win and sets status accordingly
- getGameResponse
- various helpers
- Connect 4 Game State
- player ids
- status
- columns: array of ConnectFourColumn objects which in turn are arrays of ConnectFourGameSign objects which represent player tokens or pending if nothing there yet
- winType: set to none at the start otherwise holds info about whether it was a horizontal/vertical/diagonal connect4
src/interaction-handlers/games/connectFour.ts: Interaction handlers for the buttons
This PR adds Connect 4 to Codey. More games = better? This PR does not include …

Connect 4!

---

src/components/coin.ts

Added timeout to coin transfer (currently 10 minutes), at which point transfer becomes invalid. Also now instead of displaying username in text it creates a UserMention.
resolves issue #480 
In src/components/coin.ts change the value `TransferTimeout` to some smaller value, run `.coin transfer` and wait.

add timeout to coin transfer, also ping sender and receiver in embed

---

src/components/cron.ts

A very quick change to update the office status link.

Update office status link

---

src/components/admin.ts

Rephrased ban message, first pr. 
Resolves #489.

Rephrase ban message

---

docker-compose.yml

Added the always restart line to docker compose
no downtime if bot exits due to uncaught error
Codey doesn't restart when it exits

add always restart policy for docker
