src/bot.ts
Resolves https://github.com/uwcsc/codeybot/issues/27
unpacked registerDefaults and split it into its three innate types, group, and default commands registers.
Disabled registry of default unknown command.
type any wrong command (.asopdiusaidouasipod for example), bot gives no reply.
=> removed unknownCommand error

.dockerignore, Dockerfile, Dockerfile.prod, docker-compose.yml, src/components/db.ts, src/components/logger.ts
resolves #25
resolves #8 
Added a dockerfile for production environment, which uses the `pm2` runtime to run the bot instead of `node`. The production image is also leaner than the dev image.
Building production image: `docker build . -f Dockerfile.prod -t codey-prod`
Running production container: `docker run -d --env-file .env -v $PWD/logs:/usr/app/logs -v $PWD/db:/usr/app/db codey-prod`
=> Created dockerfile for production environment

src/components/interview.ts
Followup to https://github.com/uwcsc/codeybot/pull/42
Sorted domains in codebase by alphabetical order.
Domain outputs are sorted by alphabetical order in messages.
.interviewerdomain lol
=> sorted domains for both codebase and for output

config/owners.yml
N/A
Added cneryx's discord username to owners.yml
Add "- '297185799584350208' # u rod#0019 (Chris Xie)" to config/owners.yml
=> added cneryx to owners.yml

src/commands/interviews/interviewers.ts
Resolves #108 
Mention the interviewers in the interviewer list instead of displaying their user tags
Run `.int`
=> Mention interviewers in interviewer list

src/utils/commands.ts
Resolves #111 
- Aliases do not repeat anymore
- Examples are now in inline code blocks
Invoke the help command for any command, for example, `.help int`
=> Enhanced help command

src/utils/commands.ts
N/A
Currently, admin commands only check if the user has admin privileges in the channel that the command is issued in. This means that users have full access to admin commands in DM channels.
Do `.help` in DMs with Codey and you shouldn't see any admin commands.
=> Fix admin commands in DMs

config/owners.yml
N/A
Added mcpenguin (my Discord username) to `owners.yml`, as outlined in the [Onboarding First Task](https://github.com/uwcsc/codeybot/wiki/Onboarding:-First-Task) page.
See the respective page for details.
=> Added mcpenguin to owners.yml

src/commands/coin/coinInfo.ts, src/components/coin.ts
N/A
- changed coin activity bonus to 5 mins
- related changes in coin info embed
- run `.coininfo`
- send messages within 5 mins
=> Changed coin activity bonus cooldown to 5 mins

src/commands/fun/rollDice.ts
Resolves Issue #95 
Adds command .rd n which rolls an n-sided dice and pings the user with the returned value.
=> Roll dice command

src/commands/suggestions/suggestionsList.ts, src/components/coffeechat.ts
N/A
- Fixed array size for coffee chat
- Removed the redundant alias `suggestions-list`
For the coffee chat fix, if you do `console.log(matched)`, then it should not have NaN entries anymore for when there are at least 5 people participating
=> Coffee chat and suggestion fixes

src/components/logger.ts
N/A
Error objects were not visible through the GCP log viewer because they were not serialized properly. This PR parses the error object into a string before logging.
Run `.coffeematch` on staging (erroring out ATM)
=> parse error obj to string before logging

src/components/messageListener.ts
N/A
- Modified the message listener so Codey always ignores its own messages; this would allow Codey to send a message in the honeypot channel without getting its own message deleted (and also help prevent infinite loops in general)
- Also allow a user to receive a coin bonus if their message is sent in the announcements channel
One way to test this is to make sure Codey's coin balance does not go up after sending messages
=> Modified message listener so bot ignores its own messages

.github/workflows/build.yml, src/commands/coin/coinAdjust.ts
resolves <https://github.com/uwcsc/codeybot/issues/66>
Added caching of yarn packages
Run CI pipeline on a build with cache, observe that it is now faster. Testing on this branch, the build went from 33s to 22s.
=> testing cache

src/commands/profile/profile.ts, src/components/profile.ts
resolves <https://github.com/uwcsc/codeybot/issues/189>
Previously user profile was very vertical. some fields do not need to take up an entire row. Validation was also unclear at some times so I changed that a bit. Also, I added the userprofile and aboutme alias and made profile about the default command.
Set up your user profile (.profile set <field> <description>) for multiple fields. Check out that it is not as vertical anymore.
Previous
New
=> added aliases, more validation and embed message inlining for user profiles

src/components/profile.ts
resolves <https://github.com/uwcsc/codeybot/issues/209>.
- Escaped all instances of single quote character, allowing it to be used in descriptions.
- Note that this does NOT fix the use of double quotes. It seems sapphire does not support the quotation character as part of user args as it is already removed when first received.
- .profile set aboutme SOME_DESCRIPTION_WITH_SINGLE_QUOTES
- .profile about YOUR_USERNAME
- Observe that the quotes appear properly now
=> Fix use of single quote character

src/commands/coffeeChat/coffeeChat.ts, src/components/cron.ts, src/listeners/ready.ts
Resolves #83 
Setup cronjob for coffeematch to run every friday at 10am ET.
Added cronjob start in ready.ts
Changed `alertMatch` to statis function to allow external calls from the cronjob.
Modify `coffeeChatCron`'s schedule (the 6 digit string) to activate the cronjob at whatever time you are testing.
=> Coffee chat cron

package.json, src/commands/ping/ping.ts, yarn.lock
Because slash commands is a newer feature for sapphire, it is heavily under development.
Until the dust settles down, we will be keeping sapphire framework version to `3.0.0-next.8198e94.0` unless there's some massive bug. 
Fixed deprecated options in slash command setup.
=> lock sapphire framework version and remove deprecated options

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
N/A
The assignee from issue templates is removed because this is outdated. In addition, a newly created issue is usually up for grabs, so there is now no default assignee.
The changes should be seen in the future when using an issue template
=> Cleared assignee from issue templates

src/codeyCommand.ts, src/commands/ping/ping.ts
N/A
Originally, non-slash commands used to send both the `messageWhenExecutingCommand` and the final response. Now, only `ping` would edit the message from `messageWhenExecutingCommand` to the final response and the other commands would only send the final response.
Try out the commands
=> Only edit message for ping

src/commands/profile/profile.ts
`.profile` has always felt more intuitive if it shows the caller's profile by default, this issue implements that.
=> enable profile about to default to self profile

src/bot.ts, src/codeyCommand.ts, src/commands/fun/flipCoin.ts, src/commands/fun/rollDice.ts, src/commands/info/info.ts, src/commands/miscellaneous/help.ts, src/commands/ping/ping.ts
- Added the options and subcommands functionalities into the CodeyCommand class
- Slashified the rollDice command (which requires options)
- Fixed a bug where slash commands would not be updated if they had already been registered
**Regular command**
**Slash command**
**Regular command**
**Slash command**
After using `/ping one`:
After using `/ping two`:
- The slash command parameter is type-enforced and required. In other words, you need to put in a sides parameter in order to run the command, and said parameter must be an integer.
- The `ping one` and `ping two` commands are only placeholders to verify that simple subcommands work. My next step will be to slashify coin - when I have done this, I will replace the ping back with the "original" command and show the coin screenshots …
=> Adding options and subcommands to CodeyCommand

src/codeyCommand.ts, src/commands/fun/flipCoin.ts, src/commands/fun/rollDice.ts
Made some small fixes to bugs I found after merging the previous slash commands PR.
Also, TS was complaining that the commands "flipCoin" and "rollDice" should be named lower-case, not camel case, so I've made this change accordingly.
=> Small fixes to slash commands, refactored flipcoin/rolldice

Dockerfile, docker/staging/Dockerfile
Change dockerfiles for local and staging environments to use yarn instead of node for consistency.
Update dockerfiles to use alpine 18 to prevent compatibility issues.
Once this is pushed, the same dockerfile should work for production with no extra problem.
Dockerfile tested to work in local production, waiting on staging to verify.
=> setup local dev and staging to use yarn

src/commandDetails/coin/leaderboard.ts, src/commands/coin/coin.ts, src/components/coin.ts
Added a leaderboard for the top 10 CodeyCoin holders.
Run `.coin leaderboard` or `/coin leaderboard`.
The embed is the same regardless whether you use regular or slash commands.
=> Codeycoin leaderboard

src/codeyCommand.ts
Fixed aliases for subcommands. This fix is only relevant for regular commands (slash commands don't need aliases.)
=> Fix aliases for subcommands

src/codeyCommand.ts
Fixed aliases and non-regular commands that don't have subcommands.
=> Fix aliases

src/bot.ts, src/commandDetails/coin/adjust.ts, src/commandDetails/coin/balance.ts, src/commandDetails/coin/check.ts, src/commandDetails/coin/info.ts, src/commandDetails/coin/leaderboard.ts, src/commandDetails/coin/update.ts, src/commands/games/blackjack.ts, src/components/emojis.ts
Summary of Changes
Resolves these issues.
https://github.com/uwcsc/codeybot/issues/253
https://github.com/uwcsc/codeybot/issues/254
Steps to Reproduce
The bot's status is Playing CSC | .help
Play blackjack and confirm codey coins appear properly.
=> Set activity and use codey coin emojis

package.json
Resolves #285 
Added `mkdir -p tmp` to the local:run script to make the tmp directory
When running the bot locally, see that the tmp directory is created if non-existent and no error is thrown if already existent. In addition, resume previews should now work.
=> Fixed local:run script to create tmp directory

src/components/cron.ts
https://github.com/uwcsc/codeybot/issues/228
The office hours channel should display a topic corresponding with the time on Neil's API
=> Office hours topic

src/commands/miscellaneous/info.ts, src/commands/miscellaneous/ping.ts
Move info and ping into miscellaneous folder. Prefix the command class with Miscellaneous.
https://github.com/uwcsc/codeybot/issues/303
Confirm .info and .ping work as expected.
Info and ping work as intended. No change in output.
=> Move info and ping commands to miscellaneous dir

src/bot.ts, src/events/messageCreate.ts, src/utils/embeds.ts
Migrates messageCreate logic to a discord.js based file in src/events.
Resolves https://github.com/uwcsc/codeybot/issues/315
Behaviour is confirmed to be the same with no regressions.
=> Migrate messageCreate off sapphire

src/commands/profile/profile.ts, src/components/profile.ts
- When users use .set profile year, year roles will be automatically assigned/removed.
- Manually creating new roles for each new year is tiring and could be automated. Furthermore, we have an easy way to identify alumni since the profile feature already exists.
resolves <https://github.com/uwcsc/codeybot/issues/229>
- Run .profile set <year> 
- Observe if the year is less than the current year, then you will automatically be assigned the alumni role 
- Observe that if the year is within the currentYears range identified by the original ticket known as the enum "validRoleYears" on the pr, then you will get that year assigned as a role to you.
- Observe that if the year is within the currentYears range and the role does not exist, the bot will automatically create this role.
BEFORE: …
=> automate year and alumni roles

package.json, src/bot.ts, src/codeyCommand.ts, src/commands/coffeeChat/coffeeChat.ts, src/components/db.ts, src/events/messageCreate.ts, src/events/ready.ts, src/logger/default.ts, yarn.lock
Move to winston based logger.
Winston is a popular library to log both plaintext and json. Using it allows us to show the log level, timestamp, stack traces. In the future we can use Winston to easily log warnings and errors to a file.
https://github.com/uwcsc/codeybot/issues/316
Run codey and look at the non sapphire logs in terminal.
// Two examples of warn and errro
2022-08-20 19:35:31 - warn - json warn
2022-08-20 19:35:31 - error - Error
at startBot (/usr/app/dist/src/bot.js:68:28)
at Object.<anonymous> (/usr/app/dist/index.js:4:20)
at Module._compile (node:internal/modules/cjs/loader:1120:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
at Module.load (node:internal/modules/cjs/loader:998:32)
at Module._load (node:internal/modules/cjs/loader:839:12)
at …
=> Migrate off Sapphire logger to Winston logger

.vscode/launch.json, .vscode/tasks.json, src/codeyCommand.ts, src/commandDetails/games/rps.ts, src/commands/games/rps.ts, src/components/coin.ts, src/components/db.ts, src/components/games/rps.ts, src/interaction-handlers/games/rps.ts, tsconfig.json
- Added single player RPS
- Added parameter in `tsconfig.json` that allows TS debugging on VSCode
For single player, to make it "fair", Codey takes half of your bet if you draw.
We need to kickstart the games epic, and have more games apart from just Blackjack. Moreover, the changes/logic here can be generalized for other games.
Resolves #339 (single player)
`.rps [bet]` or `/rps [bet]`
In VSCode, if you type `F5`, the debugger should also run.
Initial game screen
After clicking the rock emoji (Codey selected Rock):
Similar screens exist for winning and losing.
- Timeouts are not implemented - this should be for another issue
- This uses `interaction-handlers`, which are Sapphire-specific, so desapphirication would also need to fix those.
=> Single player RPS

.github/workflows/addCreatedIssueToBacklog.yml, .github/workflows/addCreatedIssueToProjectBoard.yml
Changed the default board issues are moved to to the "project board".
We are planning to use one project board instead of the two that are currently in place (Backlog and Active). So, we want to change the default board issues are added to in the GH action to this new "centralized" project board.
Resolves #376
=> Change default board issues are moved to project board

src/commands/profile/profile.ts
Profile picture image options changed, now includes the following options:
- dynamic (auto changes to gif for animated avatars)
- format: png
- size: 4096 
Profile pictures in user profile have better quality
Resolves #381 
src → commands → profile.ts → about function 
****
=> Update profile picture image options to enlarge image

src/commandDetails/coin/adjust.ts, src/commandDetails/coin/check.ts, src/commandDetails/coin/update.ts, src/commands/games/blackjack.ts, src/utils/pluralize.ts
Fixed pluralization of codey coin. If the user has more than 1 or 0 codey coins, the pluralization will add an s.
Better grammar :)
Resolves <https://github.com/uwcsc/codeybot/issues/299>
Any references to codey coins that rely on an amount (e.g: user updated their balance, user wins in the games that award coins) will dynamically set the pluralization.
Pluralize helper only works for codey coins right now, and should work with anything that just adds an s for pluralization. Will not work for something like mouse -> mice. This note is also on the docstring
=> Fix word pluralization

src/commandDetails/miscellaneous/info.ts
Changed the issue link in /commandDetails/miscellaneous/info to https://github.com/uwcsc/codeybot/issues/new?assignees=&labels=request&template=feature_request.md&title=%5BFEATURE%5D
More relevant page for someone that wants to request a feature.
Resolves #278 
/info command
=> Updated issue link for info

.github/workflows/build.yml
Resolves #389 
Also modifies build.yml to correctly deploy to the now separate instances for staging and production.
The new instance required newer versions of docker compose; hence the switch from `docker-compose` which is v1 to `docker compose` which is current. Modified the old instance to use the new calls as well.
once again, PRODUCTION HAS NOT BEEN TESTED UNTIL THE NEXT RELEASE. Proceed with caution.
Steps to reproduce:
tested to work successfully in the new staging instance
=> 389 split instances

src/commandDetails/coin/info.ts, src/commandDetails/coin/leaderboard.ts, src/commands/coin/coin.ts, src/commands/profile/profile.ts, src/components/coin.ts
- Fixed the bug where a user who is not on the coin leaderboard would have position #0
- Stylized `CodeyCoin` as `Codey coin`
- Removed the word "current" from the naming related to the coin leaderboard; if more leaderboards are to be added later, then adjectives can be added just for those
This fix would let a user see their correct position
Resolves #419 
Try `.coin lb` when you are not on the coin leaderboard
Without ties:
With ties:
=> Fixed position #0 in coin leaderboard

src/commandDetails/company/add.ts, src/commandDetails/company/enroll.ts, src/commandDetails/company/find.ts, src/commandDetails/company/profile.ts, src/commandDetails/company/remove.ts, src/commands/company/company.ts, src/components/companies.ts, src/components/company.ts, src/components/db.ts, src/utils/companyInfo.ts
Added company commands. That is, users can now add companies to their profile.
Allows users to find out who to contact regarding specific companies
Resolves <https://github.com/uwcsc/codeybot/issues/122>
Add CRUNCHBASE_API_KEY as a process env, you can get one from here https://www.crunchbase.com/account/integrations/crunchbase-api
There are a few pieces of work that need to be performed to make this better.
1. We should paginate for when the list of individuals that work at a company grows too large
2. Integrate this into the leaderboard feature
=> Company Commands

package.json, src/commandDetails/leetcode/leetcodeRandomCommandDetails.ts, src/commandDetails/leetcode/leetcodeSpecificCommandDetails.ts, src/commands/leetcode/leetcode.ts, src/components/leetcode.ts, src/utils/markdown.ts, yarn.lock
Added commands for leetcode:
```
.leetcode / .leetcode random [difficulty] [tag] -> Generates a random Leetcode problem with an optional filter for difficulty and tag.
.leetcode specific [problem id] -> Generates a Leetcode problem with specified ID.
```
Leetcode Bot became broken - this functionality should replace it.
Resolves #434 
Use the commands specified above.
- The Leetcode "API" might take longer than 3 seconds to run, which is the timeout for slash commands. So, instead of sending the problem via the original command, we send it as a followup message using the `afterMessageReply` functionality.
- The command is significantly faster for a search for a random problem or by a specific id compared to using filters.
=> 434 leetcode for codey

src/components/coin.ts
Added sender balance check at time of transfer handling, added enum value `Invalid` for TransferResult.
Also fixes mistake where newReceiverBalance was passed to the pluralize call for newSenderBalance.
Fixes bug where sender can start a transfer, lose coins so that they have fewer than the amount to be transferred, but still have the transfer go through. Previously the command only checked if the sender had enough at the start. 
Issue was closed, but issue#-307
=> Coin Transfer Bug Fixes

src/codeyCommand.ts
Fixing CodeyUserError to work with slash commands. Just needed to change the logging method because logging CodeyUserError with message undefined is failing JSON.stringify so only printing the error message in case of CodeyUserError. 
Fixing CodeyUserError to work with slash commands. 
Run a slash command with some validation error. 
See that the error is shown.
=> Logging changed to work with codey user error in case of slash commands

src/components/cron.ts
Uses the difference between the current and expected users with codey coin role to update roles.
It reduces API calls.
Resolves https://github.com/uwcsc/codeybot/issues/463
I don't have a guild with enough people :eyes: Please test before merging
=> Efficient API calls

src/codeyCommand.ts, src/commandDetails/games/rps.ts, src/components/games/rps.ts
Fixes RPS so it works with the dot prefix. This was just a defect in a change to codeyCommand.
Resolves #406
Resolves #405
=> Fixes rps so it works with dot prefix

src/codeyCommand.ts, src/commandDetails/fun/rollDice.ts
- Changes the sides argument of rolldice to optional, with a default value of 6.
- checks if subcommandName exists and whether it is a string
resolves issue #410
=> Issue# 410

src/config.ts, src/events/messageCreate.ts
- The bot does not crash anymore if a non-PDF file is posted in the resume channel
- Move reused hard-coded string into a constant
The bot not crashing is indisputably an improvement
Resolves #439 
For example, post an image in the resume channel and the bot does not die anymore
=> Stop bot from dying if a non-PDF file is posted in the resume channel

src/commands/coffeeChat/coffeeChat.ts, src/components/coffeeChat.ts, src/components/cron.ts
Unable to reproduce bug as described in #417 - added code that prevents a user from being matched with themself in the edge case of only one user having the role.
Resolves #417 
Run `.coffee match` with only one user holding the coffeechat role.
`.coffeechat match` was not working so I removed the `.coffeechat` examples in the command description.
=> Do not match someone with themself if only one user has coffeechat role

src/commandDetails/admin/ban.ts, src/components/admin.ts
Allows bot to ban users outside of server even if they have never joined server, previously bot could only ban users already in server.
Note: Ban Message is only sent to banned user if they are already in the server because on Discord direct messages can only be sent to users who are in mutual servers.
=> Allow bot to ban users outside server

src/commandDetails/miscellaneous/member.ts
- Made the uwid field optional instead of required
- An embed with membership info will show up if no uwid is passed in
- Resolved request #498 
I'd say my membership explanation isn't exactly the most appealing one, so I'm open to any suggestions to make it more appealing.
=> Explain the membership process when no UW ID is passed in .member

package.json, src/events/messageCreate.ts, yarn.lock
- Imported `channelMention` and `userMention` from `discord.js` for the embed
- Nuke messages without PDFs in #resume-critique 
- DM user with embed explaining why their message got nuked
- Resolve #432 
- Send a message without attachment, with non-PDF attachments, and with PDFs to see the bot in action
- I chose to use embeds for the DM because the formatting looks nicer. Still open to any suggestions to make the writing more appealing
- Not sure if we need to use `Logger` for `await message.delete()` and `await client.users.send(user, { embeds: [explainEmbed] })`
=> Enabled CodeyBot to nuke message without PDFs in #resume-critique and DM user with explanation

src/commandDetails/coin/transfer.ts, src/components/coin.ts
Upon transfers being initiated, send the receiving user a DM with a link to the transfer in order to notify them.
Also edits the transfer embed status message upon transfer completion to display user mentions instead of username
We previously added a timeout to transfers, so without the receiving user being aware of the transfer beforehand it is difficult to react and accept it within the timeout.
resolves #506 
Coordinate with a second person to test transfers, or comment out the code that prevents sending transfers to oneself.
Apologies for the delay in getting this fixed
=> Send receiver a dm on CodeyCoin transfer to notify them

README.md, docker-compose.yml, docs/COMMAND-WIKI.md, src/commandDetails/miscellaneous/help.ts, src/events/ready.ts, src/utils/updateWiki.ts
- Added script to auto-generate wiki markdown page for commands by grabbing info in implementation files
- Wiki gets updated every time CodeyBot is relaunched
- Updated wiki link of `help` command 
- Resolve #186 
- Open to any suggestions for better wiki design
=> Auto-generated Wiki Page for Commands

src/commandDetails/coin/leaderboard.ts
Changed CodeyCoin leaderboard to allow for tie handling (i.e. users with same number of CodeyCoins are ranked the same number on the leaderboard).
- A counter called absoluteCounter was introduced to keep track of the number of users iterated through on the leaderboard, to update the rank accordingly.
Previously to this commit, ties in CodeyCoin balances would result in misleading output in the leaderboard. For example, multiple users with the same balance would not be ranked the same position:
This PR fixes issue [471](https://github.com/uwcsc/codeybot/issues/471)
=> Issue# 471

src/commandDetails/coin/leaderboard.ts
- change the coin leaderboard to display user mentions instead of tags
- user mentions look nicer
- allow mentioning users on the leaderboard even if the user cannot be fetched for some reason
- resolves #517
- use `/coin leaderboard`
=> use user mentions instead of tags in coin leaderboard

src/commandDetails/admin/ban.ts
- add a log embed (similar to the one for when spammers are kicked) to when the ban command is used
- the old reply will obviously still show up
- currently, bans are only indicated as responses to the command invocation
- logs will make this information more readily available and better formatted
- resolves #436
- use `/ban`
=> add log message for bans in the notif channel

src/commandDetails/coin/leaderboard.ts
The latest leaderboard change accidentally removed suppression of an error that should not be happening. Instead of breaking when the fetched array is empty, we now stop as soon as our iterator goes beyond the end of the array. This will only happen if not enough entries were fetched to fill the fetch limit, meaning we've run out of entries.
This does not affect prod as there are enough users to avoid this, but this error breaks development (and obviously should be fixed anyway).
=> Fix leaderboard error

src/commandDetails/coin/transfer.ts, src/commandDetails/games/blackjack.ts, src/components/coin.ts, src/components/games/blackjack.ts
- currently, users can start a blackjack game, transfer their money away, and since balance cannot be negative, they are protected from losses and can get infinite money for free
- this fixes this by preventing transfers and blackjack games from ongoing concurrently
- #523
- attempt to start a blackjack game while a transfer is pending, or attempt to start a transfer while playing blackjack
=> Patch infinite money glitch by mutexing coin transfers and blackjack

src/commandDetails/games/blackjack.ts
Added more logic to try-catch block to differentiate between timeout and unexpected error. Ticket #522
=> Fixed blackjack errors deducting coins
